### PR TITLE
Downgrade version spectre.css

### PR DESCRIPTION
**Pull request by biigpongsatorn**
cuz when i deploy site to Netlify. Spectre version 0.5.1 can't download.

### CODE REVIEW

**Comment by frncsdrk** [comment]
I had the same issue locally using yarn, but using npm avoided the problem.

**Comment by biigpongsatorn** [comment]
@frncsdrk  Yes, Netlify using yarn to install dependencies.

**Comment by frncsdrk** [comment]
I did not try Netlify as hoster yet, but isn't it possible to change that to npm?

**Comment by biigpongsatorn** [comment]
try delete `yarn.lock`.

**Comment by biigpongsatorn** [comment]
Can you try deploy to github page ? I think it's better way.

**Comment by frncsdrk** [comment]
OK, will do. I'll close the issue when it is done.

**Comment by biigpongsatorn** [comment]
OK. Should we close this pull request ?

**Pull request closed without merging**
